### ISSUE TITLE
Alacritty-终端工具-性能最好的终端

### ISSUE THREAD

**Issue by try-to-fly** [InspirationAndInnovation/co-learning-and-sharing#8]
### 介绍
官网：https://alacritty.org/
介绍：Alacritty 是一种现代终端仿真器，具有合理的默认值，但允许进行广泛的配置。通过与其他应用程序集成，而不是重新实现它们的功能，它设法提供一组灵活的高性能特性。目前支持的平台包括 BSD、Linux、macOS 和 Windows。
特色：
- 据说性能最强，使用vim的程序员的首选。
- 支持半透明窗口设置

### 安装
```bash
# Arch Linux
yay -S alacritty
# Fedora/CentOS
dnf copr enable atim/alacritty
dnf install alacritty
# Debian/Ubuntu
add-apt-repository ppa:aslatter/ppa
apt install alacritty
# macOS Homebrew
brew install --cask alacritty
# Windows Scoop
scoop bucket add extras
scoop install alacritty
# Cargo on any
cargo install alacritty
```

### 配置
新建配置文件：~/.alacritty.yml
```ymll
import:
  - ~/dracula.yml
window:
  # 终端半透明
  opacity: 0.75
  startup_mode: Windowed

# 设置字体
font:
  options:
    - antialias
  normal:
    # 需要下载这个字体，才可以生效。
    family: "DroidSansMono NF"
    style: Book
  size:
    22
command:
  program: zsh
scrolling:
  history: 10000
  multiplier: 3
  auto_scroll: true
  auto_scroll_initial_max_fps: 1.0

```
